### PR TITLE
Feature/messaging api Added getStatuses and getImage endpoints 

### PR DESCRIPTION
**Pull request by athomas9195**
updated gitignore

### CODE REVIEW

**Comment by 0xMango** [comment]
Before merging, can someone fix the error in the deploy step in the backend workflow? Also was wondering if you guys think it would be better to have the backend CI trigger on pull request as well. Since Ryan doesn't like having failed runs on master branch, could you also update the ymls to trigger only when files within backend directories are changed? See `app_test.yml` as example :-)

**Comment by 0xMango** [comment]
My fault! Totally disregarded the successful check for some reason so ignore what I said

**Review by 0xMango — APPROVED** [review]

**Review by DavidSRoy — CHANGES_REQUESTED** [review]
Looking at an issue with @athomas9195 regarding running emulators

**Review by 0xMango — DISMISSED** [review]
Update `function_test.yml` to trigger only when files within backend directories are changed

**Review by DavidSRoy — APPROVED** [review]

**Pull request merged**
